name: UML Generation
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install PlantUML
      run: sudo apt-get install -y plantuml
    - name: Generate UML
      uses: j0nny/plantuml-action@v1.5
      with:
        src: ./Assets
        output: ./diagrams/UML.png
