name: Generate UML

on:
  push:
    branches:
      - master

jobs:
  generate-uml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate UML
        uses: cloudbees/plantuml-github-action@v1.2.0
        with:
          source-dir: ./
          output-dir: ./uml
          format: svg
          recursive: true
      
      - name: Commit UML files
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add UML files" || echo "No changes to commit"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
